import type { Metadata } from "next";
import { Michroma, Raleway } from "next/font/google";
import "./globals.css";
import Header from "@/components/layouts/header/Header";
import { getFirstBlogPostSlug } from "@/lib/sanity/blog";

const michroma = Michroma({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-michroma",
});

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-raleway",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Fetch first blog slug server-side for navigation
  const firstBlogPost = await getFirstBlogPostSlug();
  const firstBlogSlug = firstBlogPost?.slug?.current || null;

  return (
    <html lang="en">
      <body
        className={`${michroma.variable} ${raleway.variable} bg-[#050505] text-white antialiased`}
      >
        <Header firstBlogSlug={firstBlogSlug} />
        <main>{children}</main>
      </body>
    </html>
  );
}
